#!/usr/bin/env bash
# Cubicle installer — brings up a complete self-hosted cluster in one command.
#
#   ./install.sh                            local install on http://localhost:7000
#   ./install.sh --domain fn.example.com    public install with automatic HTTPS
#
# Re-running is safe: an existing .env is reused and secrets are never rotated.
set -euo pipefail

cd "$(dirname "$0")"

DOMAIN=""
ACME_EMAIL=""
HTTP_PORT=""
HTTPS_PORT=""
NO_START=0
STAGING=0

usage() {
	cat <<'EOF'
Usage: ./install.sh [options]

  --domain <host>     Serve on this hostname with automatic HTTPS (Let's Encrypt).
                      The hostname's DNS must already resolve to this machine.
  --email <address>   Contact address for the certificate authority.
  --http-port <n>     Host port for HTTP   (default: 80 with a domain, else 7000)
  --https-port <n>    Host port for HTTPS  (default: 443 with a domain, else 7443)
  --staging           Use the Let's Encrypt staging CA while testing.
  --no-start          Write configuration and build images, but do not start.
  -h, --help          Show this help.
EOF
}

while [ $# -gt 0 ]; do
	case "$1" in
	--domain) DOMAIN="${2:-}"; shift 2 ;;
	--email) ACME_EMAIL="${2:-}"; shift 2 ;;
	--http-port) HTTP_PORT="${2:-}"; shift 2 ;;
	--https-port) HTTPS_PORT="${2:-}"; shift 2 ;;
	--staging) STAGING=1; shift ;;
	--no-start) NO_START=1; shift ;;
	-h | --help) usage; exit 0 ;;
	*) echo "unknown option: $1" >&2; usage; exit 2 ;;
	esac
done

step() { printf '\033[1;38;5;154m▸\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ── preflight ────────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (docker compose version)."
docker info >/dev/null 2>&1 || die "Cannot talk to the Docker daemon. Is it running, and is your user in the docker group?"

gen() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-48}"; }

# ── configuration ────────────────────────────────────────────────────────────
if [ -f .env ]; then
	step "Reusing existing .env"
	# shellcheck disable=SC1091
	set -a; . ./.env; set +a
else
	step "Generating .env"
	cp .env.example .env
	POSTGRES_PASSWORD="$(gen 40)"
	CUBICLE_SECRET_KEY="$(gen 64)"
	CUBICLE_MASTER_KEY="$(gen 64)"
fi

: "${POSTGRES_PASSWORD:=$(gen 40)}"
: "${CUBICLE_SECRET_KEY:=$(gen 64)}"
: "${CUBICLE_MASTER_KEY:=$(gen 64)}"
: "${CUBICLE_VERSION:=1.0.0}"
[ -n "$DOMAIN" ] || DOMAIN="${CUBICLE_DOMAIN:-}"
[ -n "$ACME_EMAIL" ] || ACME_EMAIL="${CUBICLE_ACME_EMAIL:-}"

if [ -n "$DOMAIN" ]; then
	SITE_ADDRESS="$DOMAIN"
	PUBLIC_URL="https://$DOMAIN"
	: "${HTTP_PORT:=80}"
	: "${HTTPS_PORT:=443}"
	[ -n "$ACME_EMAIL" ] || warn "No --email given; Let's Encrypt will issue without a contact address."
else
	SITE_ADDRESS=":80"
	: "${HTTP_PORT:=7000}"
	: "${HTTPS_PORT:=7443}"
	PUBLIC_URL="http://localhost:$HTTP_PORT"
fi

# Caddy has no environment fallback for these, so they are generated as an
# imported snippet rather than smuggled through the Caddyfile as variables.
mkdir -p deploy/caddy/conf.d
{
	echo "# Generated by install.sh — edit install.sh or re-run it instead."
	[ -n "$ACME_EMAIL" ] && echo "email $ACME_EMAIL"
	[ "$STAGING" -eq 1 ] && echo "acme_ca https://acme-staging-v02.api.letsencrypt.org/directory"
	true
} >deploy/caddy/conf.d/acme.caddyfile

write_env() {
	local key="$1" value="$2"
	if grep -q "^${key}=" .env 2>/dev/null; then
		# Portable in-place edit (BSD and GNU sed disagree about -i).
		awk -v k="$key" -v v="$value" 'BEGIN{FS=OFS="="} $1==k{print k "=" v; next} {print}' .env >.env.tmp && mv .env.tmp .env
	else
		printf '%s=%s\n' "$key" "$value" >>.env
	fi
}

# A port already in use produces a confusing failure several steps later, so
# check now. On macOS, 7000 is AirPlay Receiver more often than not.
port_busy() {
	if command -v lsof >/dev/null 2>&1; then
		lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
	else
		return 1
	fi
}

if port_busy "$HTTP_PORT"; then
	warn "Port $HTTP_PORT is already in use on this machine."
	[ "$HTTP_PORT" = 7000 ] && warn "On macOS that is usually AirPlay Receiver (System Settings → General → AirDrop & Handoff)."
	if [ -z "$DOMAIN" ]; then
		for candidate in 7010 7020 7030 8070; do
			port_busy "$candidate" || { HTTP_PORT="$candidate"; break; }
		done
		PUBLIC_URL="http://localhost:$HTTP_PORT"
		warn "Using port $HTTP_PORT instead. Override with --http-port."
	else
		die "Domain mode needs port 80. Free it, or pass --http-port for a reverse proxy in front."
	fi
fi

write_env CUBICLE_VERSION "$CUBICLE_VERSION"
write_env CUBICLE_DOMAIN "$DOMAIN"
write_env CUBICLE_ACME_EMAIL "$ACME_EMAIL"
write_env CUBICLE_SITE_ADDRESS "$SITE_ADDRESS"
write_env CUBICLE_PUBLIC_URL "$PUBLIC_URL"
write_env CUBICLE_HTTP_PORT "$HTTP_PORT"
write_env CUBICLE_HTTPS_PORT "$HTTPS_PORT"
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env CUBICLE_SECRET_KEY "$CUBICLE_SECRET_KEY"
write_env CUBICLE_MASTER_KEY "$CUBICLE_MASTER_KEY"
chmod 600 .env

# ── build ────────────────────────────────────────────────────────────────────
step "Building images (first run pulls base layers — a few minutes)"
docker compose build
docker compose --profile build build runtime-py312 runtime-py311

if [ "$NO_START" -eq 1 ]; then
	step "Built. Start with: docker compose up -d"
	exit 0
fi

step "Starting the cluster"
docker compose up -d --remove-orphans

step "Waiting for the control plane"
for _ in $(seq 1 90); do
	if docker compose exec -T api python -c \
		"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/healthz',timeout=2).status==200 else 1)" \
		>/dev/null 2>&1; then
		READY=1
		break
	fi
	sleep 2
done

if [ "${READY:-0}" != "1" ]; then
	warn "The control plane did not report healthy in time. Logs:"
	docker compose logs --tail 60 api
	exit 1
fi

echo
step "Cubicle is up."
cat <<EOF

    Console      $PUBLIC_URL
    First run    open the console and complete setup — you choose the
                 administrator password there. There is no registration
                 and no account to create anywhere else.
$(
	if [ -n "$DOMAIN" ]; then
		printf '    TLS          automatic for %s (certificate issued on first request)\n' "$DOMAIN"
		printf '    Functions    https://%s/<namespace>/<function>\n' "$DOMAIN"
	else
		printf '    Functions    %s/<namespace>/<function>\n' "$PUBLIC_URL"
	fi
)
    Back up      .env (it holds CUBICLE_MASTER_KEY — without it stored
                 secrets cannot be decrypted) and the pg_data volume.

EOF
