#!/usr/bin/env bash
# Cubicle installer — brings up a complete self-hosted cluster in one command.
#
#   ./install.sh                            local install on a high, free port
#   ./install.sh --domain fn.example.com    public install with automatic HTTPS
#   ./install.sh --domain fn.example.com --behind-proxy
#                                           put it behind an nginx/Apache/Traefik
#                                           that already owns 80 and 443
#
# Re-running is safe: an existing .env is reused and secrets are never rotated.
set -euo pipefail

cd "$(dirname "$0")"

DOMAIN=""
ACME_EMAIL=""
HTTP_PORT=""
HTTPS_PORT=""
NO_START=0
STAGING=0
BEHIND_PROXY=0

usage() {
	cat <<'EOF'
Usage: ./install.sh [options]

  --domain <host>     Serve on this hostname with automatic HTTPS (Let's Encrypt).
                      The hostname's DNS must already resolve to this machine.
  --email <address>   Contact address for the certificate authority.
  --http-port <n>     Host port for HTTP   (default: 80 with a domain, else 28080)
  --https-port <n>    Host port for HTTPS  (default: 443 with a domain, else 28443)
  --behind-proxy      Do not take 80/443 or request a certificate. Serves plain
                      HTTP on a high port for an existing reverse proxy to sit
                      in front of. Requires --domain so URLs are correct.
  --staging           Use the Let's Encrypt staging CA while testing.
  --no-start          Write configuration and build images, but do not start.
  -h, --help          Show this help.
EOF
}

while [ $# -gt 0 ]; do
	case "$1" in
	--domain) DOMAIN="${2:-}"; shift 2 ;;
	--email) ACME_EMAIL="${2:-}"; shift 2 ;;
	--http-port) HTTP_PORT="${2:-}"; shift 2 ;;
	--https-port) HTTPS_PORT="${2:-}"; shift 2 ;;
	--behind-proxy) BEHIND_PROXY=1; shift ;;
	--staging) STAGING=1; shift ;;
	--no-start) NO_START=1; shift ;;
	-h | --help) usage; exit 0 ;;
	*) echo "unknown option: $1" >&2; usage; exit 2 ;;
	esac
done

step() { printf '\033[1;38;5;154m▸\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ── preflight ────────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (docker compose version)."
docker info >/dev/null 2>&1 || die "Cannot talk to the Docker daemon. Is it running, and is your user in the docker group?"

gen() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-48}"; }

# ── configuration ────────────────────────────────────────────────────────────
if [ -f .env ]; then
	step "Reusing existing .env"
	# shellcheck disable=SC1091
	set -a; . ./.env; set +a
else
	step "Generating .env"
	cp .env.example .env
	POSTGRES_PASSWORD="$(gen 40)"
	CUBICLE_SECRET_KEY="$(gen 64)"
	CUBICLE_MASTER_KEY="$(gen 64)"
fi

: "${POSTGRES_PASSWORD:=$(gen 40)}"
: "${CUBICLE_SECRET_KEY:=$(gen 64)}"
: "${CUBICLE_MASTER_KEY:=$(gen 64)}"
: "${CUBICLE_VERSION:=1.0.0}"
[ -n "$DOMAIN" ] || DOMAIN="${CUBICLE_DOMAIN:-}"
[ -n "$ACME_EMAIL" ] || ACME_EMAIL="${CUBICLE_ACME_EMAIL:-}"

# High and uncommon on purpose. Below 10000 is crowded, and at or above 32768
# is Linux's ephemeral range — the kernel hands those out to outbound
# connections, so a service parked there fails to bind intermittently and for
# reasons that look like nothing. 28080/28443 is clear of both, and clear of
# the ports every other dev tool reaches for first (3000, 5000, 8000, 8080,
# 8443, 9000).
DEFAULT_HTTP_PORT=28080
DEFAULT_HTTPS_PORT=28443

if [ "$BEHIND_PROXY" -eq 1 ]; then
	[ -n "$DOMAIN" ] || die "--behind-proxy needs --domain, so generated URLs match what your proxy serves."
	# Caddy serves plain HTTP and asks for no certificate: the proxy in front
	# already owns 80/443 and terminates TLS.
	SITE_ADDRESS=":80"
	PUBLIC_URL="https://$DOMAIN"
	: "${HTTP_PORT:=$DEFAULT_HTTP_PORT}"
	: "${HTTPS_PORT:=$DEFAULT_HTTPS_PORT}"
elif [ -n "$DOMAIN" ]; then
	SITE_ADDRESS="$DOMAIN"
	PUBLIC_URL="https://$DOMAIN"
	: "${HTTP_PORT:=80}"
	: "${HTTPS_PORT:=443}"
	[ -n "$ACME_EMAIL" ] || warn "No --email given; Let's Encrypt will issue without a contact address."
else
	SITE_ADDRESS=":80"
	: "${HTTP_PORT:=$DEFAULT_HTTP_PORT}"
	: "${HTTPS_PORT:=$DEFAULT_HTTPS_PORT}"
	PUBLIC_URL="http://localhost:$HTTP_PORT"
fi

# Caddy has no environment fallback for these, so they are generated as an
# imported snippet rather than smuggled through the Caddyfile as variables.
mkdir -p deploy/caddy/conf.d
{
	echo "# Generated by install.sh — edit install.sh or re-run it instead."
	if [ "$BEHIND_PROXY" -eq 0 ]; then
		[ -n "$ACME_EMAIL" ] && echo "email $ACME_EMAIL"
		[ "$STAGING" -eq 1 ] && echo "acme_ca https://acme-staging-v02.api.letsencrypt.org/directory"
	fi
	true
} >deploy/caddy/conf.d/acme.caddyfile

write_env() {
	local key="$1" value="$2"
	if grep -q "^${key}=" .env 2>/dev/null; then
		# Portable in-place edit (BSD and GNU sed disagree about -i).
		awk -v k="$key" -v v="$value" 'BEGIN{FS=OFS="="} $1==k{print k "=" v; next} {print}' .env >.env.tmp && mv .env.tmp .env
	else
		printf '%s=%s\n' "$key" "$value" >>.env
	fi
}

# A port already in use produces a confusing failure several steps later, so
# check now.
#
# Three probes, because no single one is available everywhere: `ss` ships with
# iproute2 on essentially every modern Linux, `lsof` is the macOS answer and is
# often absent on a minimal server, and a bash /dev/tcp connect is the last
# resort. Checking with lsof alone — as this did — silently passes on a plain
# Debian or Alpine box, which is exactly where the check matters.
PROBE=""
if command -v ss >/dev/null 2>&1; then
	PROBE="ss"
elif command -v lsof >/dev/null 2>&1; then
	PROBE="lsof"
elif command -v nc >/dev/null 2>&1; then
	PROBE="nc"
fi

port_busy() {
	case "$PROBE" in
	ss) ss -HltnO "sport = :$1" 2>/dev/null | grep -q . ;;
	lsof) lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1 ;;
	nc) nc -z 127.0.0.1 "$1" >/dev/null 2>&1 ;;
	*) return 1 ;;
	esac
}

# Best effort at naming the offender, so "port 80 is busy" becomes actionable.
port_owner() {
	case "$PROBE" in
	ss) ss -HltnpO "sport = :$1" 2>/dev/null | sed -n 's/.*users:((\"\([^\"]*\)\".*/\1/p' | head -1 ;;
	lsof) lsof -nP -iTCP:"$1" -sTCP:LISTEN -F c 2>/dev/null | sed -n 's/^c//p' | head -1 ;;
	esac
}

[ -n "$PROBE" ] || warn "Cannot check whether ports are free (no ss, lsof or nc). Install iproute2 to get this check."

# Walks upward from the requested port until a free pair turns up. Steps of 10
# so the HTTP and HTTPS ports of one install stay visibly related.
find_free_pair() {
	local http="$1" https="$2" tries=0
	while [ "$tries" -lt 40 ]; do
		if ! port_busy "$http" && ! port_busy "$https"; then
			printf '%s %s' "$http" "$https"
			return 0
		fi
		http=$((http + 10))
		https=$((https + 10))
		tries=$((tries + 1))
	done
	return 1
}

busy_ports=""
port_busy "$HTTP_PORT" && busy_ports="$HTTP_PORT"
port_busy "$HTTPS_PORT" && busy_ports="${busy_ports:+$busy_ports and }$HTTPS_PORT"

if [ -n "$busy_ports" ]; then
	owner="$(port_owner "$HTTP_PORT")"
	[ -n "$owner" ] || owner="$(port_owner "$HTTPS_PORT")"
	warn "Port $busy_ports already in use${owner:+ (by $owner)}."
	case "$HTTP_PORT" in
	7000) warn "On macOS that is usually AirPlay Receiver (System Settings → General → AirDrop & Handoff)." ;;
	esac

	# Automatic HTTPS is the one case a different port cannot rescue: the CA
	# validates by connecting to 80 and 443 itself, so nothing else will do.
	if [ -n "$DOMAIN" ] && [ "$BEHIND_PROXY" -eq 0 ]; then
		other="${owner:-the other server}"
		echo
		warn "Automatic HTTPS needs ports 80 and 443 — Let's Encrypt connects to"
		warn "them itself, so moving Cubicle to another port cannot stand in."
		echo
		echo "  1. Stop $other and re-run this script."
		echo
		echo "  2. Keep $other in front and run Cubicle behind it:"
		echo
		echo "       ./install.sh --domain $DOMAIN --behind-proxy"
		echo
		echo "     Cubicle serves plain HTTP on a high port, $other terminates"
		echo "     TLS, and this script prints a server block to paste in."
		echo
		die "Ports 80 and 443 are not available."
	fi

	if pair="$(find_free_pair "$HTTP_PORT" "$HTTPS_PORT")"; then
		HTTP_PORT="${pair% *}"
		HTTPS_PORT="${pair#* }"
		warn "Using $HTTP_PORT and $HTTPS_PORT instead. Override with --http-port / --https-port."
		[ -n "$DOMAIN" ] || PUBLIC_URL="http://localhost:$HTTP_PORT"
	else
		die "Could not find a free port pair near $HTTP_PORT. Pass --http-port and --https-port."
	fi
fi

write_env CUBICLE_VERSION "$CUBICLE_VERSION"
write_env CUBICLE_DOMAIN "$DOMAIN"
write_env CUBICLE_ACME_EMAIL "$ACME_EMAIL"
write_env CUBICLE_SITE_ADDRESS "$SITE_ADDRESS"
write_env CUBICLE_PUBLIC_URL "$PUBLIC_URL"
write_env CUBICLE_HTTP_PORT "$HTTP_PORT"
write_env CUBICLE_HTTPS_PORT "$HTTPS_PORT"
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env CUBICLE_SECRET_KEY "$CUBICLE_SECRET_KEY"
write_env CUBICLE_MASTER_KEY "$CUBICLE_MASTER_KEY"
chmod 600 .env

# ── build ────────────────────────────────────────────────────────────────────
step "Building images (first run pulls base layers — a few minutes)"
docker compose build
docker compose --profile build build runtime-py312 runtime-py311

if [ "$NO_START" -eq 1 ]; then
	step "Built. Start with: docker compose up -d"
	exit 0
fi

step "Starting the cluster"
docker compose up -d --remove-orphans

step "Waiting for the control plane"
for _ in $(seq 1 90); do
	if docker compose exec -T api python -c \
		"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/healthz',timeout=2).status==200 else 1)" \
		>/dev/null 2>&1; then
		READY=1
		break
	fi
	sleep 2
done

if [ "${READY:-0}" != "1" ]; then
	warn "The control plane did not report healthy in time. Logs:"
	docker compose logs --tail 60 api
	exit 1
fi

echo
step "Cubicle is up."
cat <<EOF

    Console      $PUBLIC_URL
    First run    open the console and complete setup — you choose the
                 administrator password there. There is no registration
                 and no account to create anywhere else.
$(
	if [ "$BEHIND_PROXY" -eq 1 ]; then
		printf '    Listening    http://127.0.0.1:%s — put your proxy in front of it\n' "$HTTP_PORT"
		printf '    TLS          handled by your existing server, not by Cubicle\n'
		printf '    Functions    https://%s/<namespace>/<function>\n' "$DOMAIN"
	elif [ -n "$DOMAIN" ]; then
		printf '    TLS          automatic for %s (certificate issued on first request)\n' "$DOMAIN"
		printf '    Functions    https://%s/<namespace>/<function>\n' "$DOMAIN"
	else
		printf '    Functions    %s/<namespace>/<function>\n' "$PUBLIC_URL"
	fi
)
    Back up      .env (it holds CUBICLE_MASTER_KEY — without it stored
                 secrets cannot be decrypted) and the pg_data volume.

EOF

if [ "$BEHIND_PROXY" -eq 1 ]; then
	cat <<EOF
──────────────────────────────────────────────────────────────────────────────
Add this to nginx, then reload it. The buffering and timeout lines are not
optional: Cubicle streams the live log tail and the activity dashboard over
server-sent events, and nginx buffers proxied responses by default, which
turns a live stream into a connection that appears to hang.

server {
    listen 443 ssl;
    server_name $DOMAIN;

    # your existing certificate lines here

    location / {
        proxy_pass         http://127.0.0.1:$HTTP_PORT;
        proxy_http_version 1.1;

        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;

        # Server-sent events: no buffering, and long enough to outlive a
        # function's timeout.
        proxy_buffering    off;
        proxy_cache        off;
        proxy_read_timeout 15m;
    }
}
──────────────────────────────────────────────────────────────────────────────

EOF
fi
