"""Teaching the edge about apps.

Functions are reached through the control plane, so the edge configuration for
them never changes. An app is different: it holds hostnames, and Caddy has to
know each one both to route it and to get a certificate for it.

Caddy is configured from a file rather than its admin API — the API is switched
off deliberately, and an install should be inspectable by reading a file. So the
control plane writes one fragment into a volume both containers share, and asks
Caddy to reload. A reload is graceful: the old config keeps serving until the
new one is accepted, and a fragment that fails to parse leaves the running
configuration exactly where it was.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import docker

from ..logging_setup import log
from .engine import LOCAL_HOST, engines

#: Shared with the caddy container. Written here, read there.
FRAGMENT_DIR = Path("/etc/caddy/apps")
FRAGMENT = FRAGMENT_DIR / "apps.caddyfile"

#: The container to ask for a reload. Compose names it; an install that renames
#: it can say so in the environment.
CADDY_CONTAINER = "cubicle-caddy-1"

#: Where Caddy listens for administrative commands. A socket, so a reload is
#: possible without the admin API being on a port anything could reach.
ADMIN_SOCKET = "unix//run/caddy-admin.sock"

HEADER = """\
# Generated by Cubicle. Do not edit — every app deploy rewrites this file.
#
# One site block per hostname, one upstream per replica. Caddy obtains a
# certificate for each hostname on its first request, so DNS pointing here is
# the only prerequisite.
"""


def render(routes: list[dict], *, tls: bool) -> str:
    """Turn the app routing table into a Caddyfile fragment.

    ``routes`` is ``[{"hostname": ..., "upstreams": [...], "app": ...}]``.
    Upstreams are container names on the edge network; several of them make
    Caddy round-robin, which is what a replica count means in practice.

    ``tls`` says whether this instance terminates TLS, and it decides the site
    address rather than only the certificate. A bare hostname turns on Caddy's
    automatic HTTPS: it serves the host on 443 and leaves port 80 as a redirect.
    On an install with no domain nothing can issue that certificate, and the
    main site — which is the catch-all `:80` — would answer the app's hostname
    with the console instead. So without TLS the app is bound to http://
    explicitly, which both beats the catch-all and actually serves.
    """
    blocks = [HEADER]
    for route in sorted(routes, key=lambda r: r["hostname"]):
        upstreams = " ".join(route["upstreams"])
        if not upstreams:
            continue
        address = route["hostname"] if tls else f"http://{route['hostname']}"
        blocks.append(
            f"# {route['app']}\n"
            f"{address} {{\n"
            f"\thandle /.cubicle-health {{\n"
            f"\t\trespond \"ok\" 200\n"
            f"\t}}\n"
            f"\treverse_proxy {upstreams} {{\n"
            # An app that is mid-restart should not become a 502 for the
            # caller: Caddy takes a failed upstream out of rotation and, with
            # one replica, retries it for a couple of seconds first.
            f"\t\tlb_policy round_robin\n"
            f"\t\tlb_try_duration 5s\n"
            f"\t\tfail_duration 10s\n"
            f"\t}}\n"
            f"}}\n"
        )
    return "\n".join(blocks)


def _digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:12]


async def apply(routes: list[dict], *, tls: bool) -> bool:
    """Write the fragment and reload Caddy. True when the edge changed.

    Never raises: an app that is running but not yet routable is a better
    outcome than a deploy that reports failure after the container came up.
    The error is logged and surfaced through the app's own status instead.
    """
    config = render(routes, tls=tls)
    try:
        FRAGMENT_DIR.mkdir(parents=True, exist_ok=True)
        current = FRAGMENT.read_text() if FRAGMENT.exists() else ""
        if _digest(current) == _digest(config):
            return False
        FRAGMENT.write_text(config)
    except OSError as exc:
        log.warning("could not write the edge fragment", error=str(exc))
        return False

    return await reload()


async def reload() -> bool:
    """Ask Caddy to pick the fragment up. Graceful; keeps serving on failure."""

    def _reload(client: docker.DockerClient) -> tuple[int, str]:
        container = client.containers.get(CADDY_CONTAINER)
        result = container.exec_run(
            [
                "caddy",
                "reload",
                "--config",
                "/etc/caddy/Caddyfile",
                "--adapter",
                "caddyfile",
                "--address",
                ADMIN_SOCKET,
            ]
        )
        return result.exit_code, result.output.decode("utf-8", "replace")[-2000:]

    try:
        code, output = await engines.call(LOCAL_HOST, _reload)
    except Exception as exc:  # noqa: BLE001 - reported, never fatal to a deploy
        log.warning("could not reach the edge to reload it", error=str(exc))
        return False

    if code != 0:
        log.warning("edge reload refused the configuration", output=output)
        # A reload that cannot happen leaves apps unreachable, which is worse
        # than the second of dropped connections a restart costs. The config is
        # already on disk and valid as far as we can tell, so pick it up the
        # blunt way rather than leaving the edge stale.
        return await _restart()
    log.info("edge reloaded")
    return True


async def _restart() -> bool:
    def _bounce(client: docker.DockerClient) -> None:
        client.containers.get(CADDY_CONTAINER).restart(timeout=10)

    try:
        await engines.call(LOCAL_HOST, _bounce)
    except Exception as exc:  # noqa: BLE001 - reported through the app's status
        log.warning("could not restart the edge", error=str(exc))
        return False
    log.warning("edge restarted to pick up routing (reload was refused)")
    return True
