from . import (
    ai,
    auth,
    cluster,
    clusters,
    config,
    data_services,
    database,
    functions,
    invoke,
    live,
    observability,
    reconcile,
    redis_browser,
    runtimes,
    settings,
    setup,
    update,
)

ROUTERS = [
    setup.router,
    ai.router,
    auth.router,
    clusters.router,
    functions.router,
    config.router,
    observability.router,
    live.router,
    cluster.router,
    data_services.router,
    database.router,
    redis_browser.router,
    reconcile.router,
    runtimes.router,
    settings.router,
    update.router,
    invoke.router,
]

__all__ = ["ROUTERS"]
